name: sa-comparison
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.3.2
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jpeg=9c
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libpng=1.6.36
  - libsodium=1.0.16
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1b
  - pandas=0.24.1
  - parso=0.3.4
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pip=19.0.3
  - prompt_toolkit=2.0.9
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyzmq=18.0.0
  - qt=5.9.7
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tornado=6.0.1
  - traitlets=4.3.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - wheel=0.33.1
  - wincertstore=0.2
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - SALib==1.2
